NDLANO/image-api

build.sbt
src/main/scala/no/ndla/imageapi/ImageApiProperties.scala

Avhengig av ack og release av network

#174: Tatt ibruk fellesfunksjonalitet for Domain

---

src/main/scala/no/ndla/imageapi/service/ImportService.scala
src/main/scala/no/ndla/imageapi/service/TagsService.scala
src/test/scala/no/ndla/imageapi/service/TagsServiceTest.scala

Hater å slette testene, men fant ikke noen måte å faktorisere de ut. Tar gjerne imot tips :)

#190: Håndterer at noder ikke gjenfinnes i tags-tjenesten

---

build.sbt
src/main/scala/no/ndla/imageapi/integration/MigrationApiClient.scala

Henger sammen med https://github.com/NDLANO/article-api/pull/89

#86 network lib update

---

src/main/scala/no/ndla/imageapi/service/ConverterService.scala

Glemte å fjerne de 2 funksjonene i forrige PR

#466 Removed unused functions

---

src/main/scala/no/ndla/imageapi/service/ImportService.scala

Prosent encode URLer til bilder. Reimporterer alle bilder etter denne er merget

percent encode urls in import #585

---

src/main/scala/no/ndla/imageapi/controller/InternController.scala
src/main/scala/no/ndla/imageapi/service/search/IndexService.scala
src/test/scala/no/ndla/imageapi/controller/InternControllerTest.scala

GlobalDigitalLibraryio/issues#72
Based on changes made in https://github.com/GlobalDigitalLibraryio/image-api/pull/4

#72: Endpoint for removal of all indexes

---

src/main/scala/no/ndla/imageapi/model/api/Error.scala
src/main/scala/no/ndla/imageapi/model/api/ValidationError.scala
src/test/scala/no/ndla/imageapi/controller/HealthControllerTest.scala

GlobalDigitalLibraryio/issues#72

#72: Fix spelling mistakes

---

src/main/scala/no/ndla/imageapi/controller/HealthController.scala
src/main/scala/no/ndla/imageapi/repository/ImageRepository.scala
src/test/scala/no/ndla/imageapi/controller/HealthControllerTest.scala

Healtcheck now fetches a random image from database rather than
searching first.

#812: health-check now fetches a random image from database

---

src/main/scala/no/ndla/imageapi/model/Language.scala
src/main/scala/no/ndla/imageapi/model/api/ImageMetaSummary.scala
src/main/scala/no/ndla/imageapi/service/ConverterService.scala
src/main/scala/no/ndla/imageapi/service/search/SearchConverterService.scala
src/test/scala/no/ndla/imageapi/controller/ImageControllerV2Test.scala
src/test/scala/no/ndla/imageapi/service/ConverterServiceTest.scala
src/test/scala/no/ndla/imageapi/service/search/SearchServiceIntegrationTest.scala

Adds `supportedLanguages` for search and sorts the single image `supportedLanguages`

#741: Adds supportedLanguages for search

---

src/main/scala/no/ndla/imageapi/service/ImageStorageService.scala
src/test/scala/no/ndla/imageapi/integration/ImageStorageServiceTest.scala

https://github.com/GlobalDigitalLibraryio/image-api/pull/23

#915: Consume stream immediately and close it

---

src/main/scala/no/ndla/imageapi/JettyLauncher.scala
src/main/scala/no/ndla/imageapi/service/ImageStorageService.scala
src/main/scala/no/ndla/imageapi/service/search/IndexBuilderService.scala
src/main/scala/no/ndla/imageapi/service/search/IndexService.scala
src/test/scala/no/ndla/imageapi/integration/ImageStorageServiceTest.scala

resolves https://github.com/NDLANO/Issues/issues/1069

#1069: Adds cleanup after updating aliasTarget

---

build.sbt
src/main/scala/no/ndla/imageapi/ImageApiProperties.scala
src/main/scala/no/ndla/imageapi/JettyLauncher.scala

Added javamelody to component

---

src/main/scala/no/ndla/imageapi/service/ImportService.scala
src/test/scala/no/ndla/imageapi/service/ImportServiceTest.scala

#499: Only import tags in relevant languages

---

build.sbt
src/main/scala/no/ndla/imageapi/ImageApiProperties.scala

connected to NDLANO/Issues#1439

update network library version #1439

---

src/main/scala/no/ndla/imageapi/ImageSwagger.scala
src/main/scala/no/ndla/imageapi/controller/ImageControllerV2.scala

Removed oauth from get and refreshed docs.

---

src/main/scala/no/ndla/imageapi/ComponentRegistry.scala
src/main/scala/no/ndla/imageapi/ImageApiProperties.scala

connects to NDLANO/Issues#1545

#1545: Use correct s3 bucket name and region in new environment

---

src/main/scala/no/ndla/imageapi/service/search/SearchService.scala
src/test/scala/no/ndla/imageapi/service/search/ImageSearchServiceTest.scala

Gjør det mulig å søke etter bilder med id til bildet.

Added search for id

---

src/main/scala/no/ndla/imageapi/service/ValidationService.scala
src/main/scala/no/ndla/imageapi/service/WriteService.scala
src/test/scala/no/ndla/imageapi/service/ValidationServiceTest.scala
src/test/scala/no/ndla/imageapi/service/WriteServiceTest.scala

Connects to NDLANO/Issues#1584

#1584: Change validation rules to accept unknown lang if already present

---

src/main/scala/no/ndla/imageapi/JettyLauncher.scala

Fulgte oppskrifta nederst her: http://scalatra.org/guides/2.6/web-services/cors.html

Allow showing images from other sitest

---

src/main/scala/no/ndla/imageapi/controller/InternController.scala
src/main/scala/no/ndla/imageapi/controller/NdlaController.scala
src/main/scala/no/ndla/imageapi/model/api/ImageMetaDomainDump.scala
src/main/scala/no/ndla/imageapi/model/domain/ImageApiModels.scala
src/main/scala/no/ndla/imageapi/repository/ImageRepository.scala
src/main/scala/no/ndla/imageapi/service/ReadService.scala

Partly fixes NDLANO/Issues#2105

#2105: Adds domain dump endpoints to intern controller

---

src/main/scala/no/ndla/imageapi/JettyLauncher.scala
src/main/scala/no/ndla/imageapi/controller/ImageControllerV2.scala
src/main/scala/no/ndla/imageapi/model/NDLAErrors.scala
src/main/scala/no/ndla/imageapi/model/api/Author.scala
src/main/scala/no/ndla/imageapi/service/ConverterService.scala
src/main/scala/no/ndla/imageapi/service/ImportService.scala
src/main/scala/no/ndla/imageapi/service/ReadService.scala
src/main/scala/no/ndla/imageapi/service/WriteService.scala
src/test/scala/no/ndla/imageapi/service/ConverterServiceTest.scala
src/test/scala/no/ndla/imageapi/service/ImportServiceTest.scala
src/test/scala/no/ndla/imageapi/service/WriteServiceTest.scala

Litt essensielt at tag-indeksen blir oppdatert når bilder lagres 🤦

Fix indexing and deleting tag documents on image store/update/delete

---

src/main/scala/no/ndla/imageapi/controller/ImageControllerV2.scala
src/main/scala/no/ndla/imageapi/controller/NdlaController.scala
src/main/scala/no/ndla/imageapi/model/api/UpdateImageMetaInformation.scala
src/main/scala/no/ndla/imageapi/service/ConverterService.scala
src/main/scala/no/ndla/imageapi/service/ImageStorageService.scala
src/main/scala/no/ndla/imageapi/service/WriteService.scala
src/test/scala/no/ndla/imageapi/controller/ImageControllerV2Test.scala

Relates to NDLANO/Issues#2504
Lar oss oppdatere bildefiler for eksisterende bilder

#2504: Implement updating file for existing images

---

src/main/scala/no/ndla/imageapi/service/ImageConverter.scala

Fixes NDLANO/Issues#2526
Problemet var at bildet hadde gjennomsiktige pixler (Som ikke er støttet av jpeg)
Løser problemet ved å fylle inn de gjennomsiktige med hvit farge dersom de finnes og bildet er jpeg

#2526: Fill in transparent pixels for jpeg images

---

src/main/scala/no/ndla/imageapi/model/api/ImageMetaSummary.scala
src/main/scala/no/ndla/imageapi/service/search/SearchConverterService.scala
src/test/scala/no/ndla/imageapi/controller/ImageControllerV2Test.scala
src/test/scala/no/ndla/imageapi/service/search/ImageSearchServiceTest.scala

Relatert til NDLANO/Issues#2848
Legger til lastUpdated som felt i søkeresultat

2848 more search data
